# Generated by Django 4.1.3 on 2023-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelLearned', models.IntegerField()),
                ('move', models.CharField(max_length=100)),
            ],
        ),
    ]
