# Generated by Django 4.1.3 on 2023-01-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_newmove'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewMove',
            new_name='Attack',
        ),
    ]
