# Generated by Django 4.1.3 on 2023-01-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_attack_delete_evolve'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='pokemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.pokemon'),
            preserve_default=False,
        ),
    ]
