# Generated by Django 4.1.3 on 2023-01-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_item_pokemon_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='move',
            field=models.CharField(choices=[('T', 'Tackle'), ('S', 'Scratch'), ('E', 'Ember'), ('W', 'Water Gun'), ('V', 'Vine Whip'), ('R', 'Rock Smash'), ('Th', 'Thundershock')], default='T', max_length=100),
        ),
    ]
